apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking
  labels:
    app: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
        - name: banking
          image: rathinamn/banking:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-secret
