apiVersion: v1
kind: Service
metadata:
  name: getting-started-app-service
  labels:
    app: getting-started-app
spec:
  type: NodePort
  selector:
    app: getting-started-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
