apiVersion: v1
kind: Service
metadata:
  name: banking-service
  labels:
    app: banking
spec:
  type: NodePort   # allows external access from EC2
  selector:
    app: banking
  ports:
    - port: 8080
      targetPort: 8082
     
